global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    scrape_interval: 10s
    metrics_path: '/metrics'

  - job_name: 'order-service-actuator'
    static_configs:
      - targets: ['order-service:8080']
    scrape_interval: 15s
    metrics_path: '/actuator/prometheus'

  - job_name: 'inventory-service-actuator'
    static_configs:
      - targets: [ 'inventory-service:8080' ]
    scrape_interval: 15s
    metrics_path: '/actuator/prometheus'

  - job_name: 'user-service-actuator'
    static_configs:
      - targets: ['user-service:8080']  # Fixed port
    scrape_interval: 15s
    metrics_path: '/actuator/prometheus'

  - job_name: 'payment-service-actuator'
    static_configs:
      - targets: ['payment-service:8080']  # Fixed port
    scrape_interval: 15s
    metrics_path: '/actuator/prometheus'


  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch-exporter:9114']
    scrape_interval: 30s
    metrics_path: '/metrics'